# STEP 1 build executable binary
FROM golang:alpine as builder
COPY . $GOPATH/src/localhost.com/go-demo/protobuf-app
WORKDIR $GOPATH/src/localhost.com/go-demo/protobuf-app

# build the binary
RUN go build -o /go/bin/client $GOPATH/src/localhost.com/go-demo/protobuf-app/cmd/client/client.go

# STEP 2 build a small image
# start from scratch
FROM scratch
# Copy our startic executable
COPY --from=builder /go/bin/client /go/bin/client
ENTRYPOINT = ["/go/bin/client"]